//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3LayerApp.DAL.Entities
{

    public partial class Transaction
    {
        public int TransactionId { get; set; }
        public int TransactionTypeId { get; set; }
        public decimal Amount { get; set; }
        public int AccountId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
